#!/usr/bin/env bash

set -u

PROGRAM=${0##*/}
STATE_ROOT=${SECURE_DIR_STATE_ROOT:-"$HOME/.local/share/secure-dir"}
PORTAL_ROOT=${SECURE_DIR_PORTAL_ROOT:-"$HOME/Secure"}
TTY_DEVICE=${SECURE_DIR_TTY:-/dev/tty}

usage() {
	cat <<EOF
Usage:
  $PROGRAM init NAME [PORTAL]
  $PROGRAM unlock NAME [PORTAL]
  $PROGRAM lock NAME [PORTAL]
  $PROGRAM status NAME [PORTAL]

Manage an EncFS-backed directory that direnv unlocks on entry.

The encrypted data is stored under:
  $STATE_ROOT/NAME/cipher

The default portal is:
  $PORTAL_ROOT/NAME

Its decrypted contents are mounted at PORTAL/files. Nothing is mounted at
boot, so secure directories start locked after a restart.
EOF
}

die() {
	echo "$PROGRAM: $*" >&2
	exit 1
}

require_command() {
	command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

validate_name() {
	case "$1" in
		""|.|..|*[!A-Za-z0-9._-]*)
			die "NAME may contain only letters, numbers, dot, underscore, and hyphen"
			;;
	esac
}

set_paths() {
	NAME=$1
	validate_name "$NAME"

	if [ "$#" -ge 2 ]; then
		PORTAL=$2
	else
		PORTAL=$PORTAL_ROOT/$NAME
	fi

	case "$PORTAL" in
		/*) ;;
		*) die "PORTAL must be an absolute path" ;;
	esac

	VAULT=$STATE_ROOT/$NAME
	CIPHER=$VAULT/cipher
	MOUNT=$PORTAL/files
	CONFIG=$CIPHER/.encfs6.xml
}

is_mounted() {
	if command -v mountpoint >/dev/null 2>&1; then
		mountpoint -q "$MOUNT"
		return
	fi

	[ -d "$MOUNT" ] || return 1
	if [ "$(uname -s)" = Darwin ]; then
		[ "$(stat -f %d "$MOUNT")" != "$(stat -f %d "$MOUNT/..")" ]
	else
		[ "$(stat -c %d "$MOUNT")" != "$(stat -c %d "$MOUNT/..")" ]
	fi
}

unmount_path() {
	if [ "$(uname -s)" = Darwin ]; then
		umount "$MOUNT"
	elif command -v fusermount3 >/dev/null 2>&1; then
		fusermount3 -u "$MOUNT"
	elif command -v fusermount >/dev/null 2>&1; then
		fusermount -u "$MOUNT"
	else
		umount "$MOUNT"
	fi
}

write_envrc() {
	local quoted_name
	quoted_name=$(printf '%q' "$NAME")

	cat > "$PORTAL/.envrc" <<EOF
# Generated by secure-dir.sh. Re-run "secure-dir.sh init $quoted_name" to replace it.
if ! command -v secure-dir.sh >/dev/null 2>&1; then
  echo "secure-dir: secure-dir.sh is not available on PATH" >&2
  return 1
fi

secure-dir.sh unlock $quoted_name "\$PWD"
EOF
	chmod 600 "$PORTAL/.envrc"
}

init_vault() {
	require_command encfs

	[ ! -e "$CONFIG" ] || die "vault already initialized: $NAME"
	[ ! -e "$PORTAL/.envrc" ] || die "refusing to replace existing $PORTAL/.envrc"

	umask 077
	mkdir -p "$CIPHER" "$MOUNT"
	chmod 700 "$VAULT" "$CIPHER" "$PORTAL" "$MOUNT"

	echo "$PROGRAM: creating EncFS vault $NAME" >&2
	echo "$PROGRAM: choose and confirm its password when EncFS prompts" >&2
	if ! encfs --standard "$CIPHER" "$MOUNT" <"$TTY_DEVICE"; then
		die "EncFS initialization failed; no direnv configuration was created"
	fi

	if is_mounted && ! unmount_path; then
		die "vault was created but could not be unmounted; run '$PROGRAM lock $NAME'"
	fi

	write_envrc
	echo "$PROGRAM: initialized $NAME" >&2
	echo "$PROGRAM: run 'direnv allow $PORTAL' once to enable automatic unlocking" >&2
}

unlock_vault() {
	require_command encfs
	[ -f "$CONFIG" ] || die "vault is not initialized: $NAME"
	mkdir -p "$MOUNT"
	chmod 700 "$MOUNT"

	if is_mounted; then
		return 0
	fi

	[ -r "$TTY_DEVICE" ] || die "cannot prompt for the password without an interactive terminal"
	echo "$PROGRAM: $NAME is locked; enter its EncFS password" >&2
	encfs "$CIPHER" "$MOUNT" <"$TTY_DEVICE"
}

lock_vault() {
	[ -f "$CONFIG" ] || die "vault is not initialized: $NAME"

	if ! is_mounted; then
		echo "$PROGRAM: $NAME is already locked" >&2
		return 0
	fi

	unmount_path || die "could not unmount $MOUNT; files may still be open"
	echo "$PROGRAM: locked $NAME" >&2
}

status_vault() {
	if [ ! -f "$CONFIG" ]; then
		echo "$NAME: uninitialized"
		return 2
	fi

	if is_mounted; then
		echo "$NAME: unlocked ($MOUNT)"
	else
		echo "$NAME: locked"
	fi
}

COMMAND=${1:-}
case "$COMMAND" in
	-h|--help|help)
		usage
		exit 0
		;;
esac

[ "$#" -ge 2 ] && [ "$#" -le 3 ] || {
	usage >&2
	exit 2
}

shift
set_paths "$@"

case "$COMMAND" in
	init) init_vault ;;
	unlock) unlock_vault ;;
	lock) lock_vault ;;
	status) status_vault ;;
	*)
		usage >&2
		die "unknown command: $COMMAND"
		;;
esac
